### PR TITLE
TTOOLS-337 AddConnectionWizard rework for openshift

### PR DESCRIPTION
**Pull request by mdrillin**
NOTE: this PR has a corresponding teiid-komodo PR.  Also note with this checkin that deployment to openshift will be required to create 'connections' - since ServiceCatalogDatasources are utilized to create connections.
- The beetle studio 'AddConnection' wizard has been reworked to utilize ServiceCatalogDataSources.  The user selects a type of connection, then selects the catalog datasource to use.
- User is also allowed to edit an existing connection.

### CODE REVIEW

**Review by phantomjinx — APPROVED** [review]
Looks good. Probably merge after the demo and once its sister PR has been merged in teiid-komodo.

**Review by elvisisking — APPROVED** [review]
Looks good Mark!

**Review by tejones — APPROVED** [review]
Lookin' good! (ala Freddie Prinze)

**Comment by mdrillin** [comment]
Amended the PR to work with changes requested on the teiid-komodo PR.

**Pull request merged**
